### ISSUE TITLE
Delete attachements

### ISSUE THREAD

**Issue by Ruriko** [michaeluno/Task-Scheduler#10]
So I set it to auto delete posts that are older than a day but I want it to also delete attachments since some posts contain linked attachments.  Can you make it auto delete attachments as well?

**Comment by michaeluno** [comment]
Hi, 

Are those posts with attachments built-in post types? Or are they custom post types?

**Comment by Ruriko** [comment]
They are built-in post types

**Comment by michaeluno** [comment]
Can you post screenshots so that I'll understand what you are talking about?

**Comment by Ruriko** [comment]
Ok so I create a post and upload some images which gets automatically added to the media library. Using task scheduler it can delete the post but it does not delete the image that's included in the post cause you can still see it in the media library. 

Here is screenshot for attachments [http://i.imgur.com/P8g4fX2.jpg](url) as you can see the screenshot shows the image is attached to the post named "Test". So if the post "Test" is deleted it should delete that image as well

**Comment by michaeluno** [comment]
I see. 

So when the user selects the `attachment` post type, the attached files should be also deleted. 

I'll see what I can do.

**Comment by michaeluno** [comment]
It turned out to be a bug in the Delete Action module component which ignored posts without taxonomy items. 

@Ruriko Can you try the [1.4.4b](https://github.com/michaeluno/Task-Scheduler/tree/1.4.4b) branch which should fix this issue?

**Comment by Ruriko** [comment]
yep it's working now

**Comment by michaeluno** [comment]
The version 1.4.4 has been released. Thanks for the report.
