### ISSUE TITLE
internacionalizacion

### ISSUE THREAD

**Issue by QHADI** [michaeluno/Task-Scheduler#12]
Localization error at wordpress.org. Can not translate
https://translate.wordpress.org/projects/wp-plugins/task-scheduler

This plugin is not properly prepared for localization (View detailed logs on Slack). If you would like to translate this plugin, please contact the author.

**Comment by michaeluno** [comment]
Thanks for the report. v1.4.6 has been released and it now includes the default language file so that translators can create their own language files.
