### ISSUE TITLE
 How does Task-scheduler schedule tasks without depending on page-load?

### ISSUE THREAD

**Issue by iamlearningdeveloper** [michaeluno/Task-Scheduler#13]
Hi,

Can you please let me know that how does this plugin schedule taks without depending on page load. I looked into code but could not understand how can it schedule a task if there is no visitor to the site? 

PS: I know this is not a support question but found the forum pretty inactive so posted here. Apologies for the same.

**Comment by michaeluno** [comment]
Hi,

It actually relies on page load done in the background by Server Heartbeat. It uses [HTTP API](https://codex.wordpress.org/HTTP_API) and keeps accessing the site itself. Created tasks are stored as a post with a custom post type. In every background page load, the plugin checks whether there are tasks close to the current time. And those found tasks are picked and wait for the execution time and run in another separate background page load.

**Comment by NishantGar** [comment]
But I have one question. For loading page via HTTP API, what do you do?
* Is it via some **system cron** job checking for background task in every minute and loading a page via HTTP API when some tasks need to be run?
* Or is it that you keep calling the HTTP API continuously. If that's the case, don't many hosting providers block you for using the resources even when no real-visitor is coming to your website?

Thanks, @michaeluno for really nice gesture for the previous detailed answer.
