### ISSUE TITLE
Bug report on TaskScheduler_Occurrent_Daily.php line 69

### ISSUE THREAD

**Issue by quynhcvn** [michaeluno/Task-Scheduler#16]
Error on "task-scheduler\include\class\module\occurrence\daily\TaskScheduler_Occurrent_Daily.php", line 69 when we set a daily schedule to run the PHP script.

Error message:
"Fatal error: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in:...task-scheduler\include\class\module\occurrence\daily\TaskScheduler_Occurrent_Daily.php:69 Stack...".

I tried to change the below code on line 69 of this PHP file, then the error disappear:
From: $_iLastRunTime = round( $nLastRunTime );
To: $_iLastRunTime = $nLastRunTime;

**Comment by michaeluno** [comment]
Hi,

Can you provide the steps to reproduce it? 

By the way, I'd suggest the following change

```php
$_iLastRunTime = round( $nLastRunTime );
```
to
```php
$_iLastRunTime = round( ( integer ) $nLastRunTime );
```

Also, please provide PHP and WordPress versions. Thank you.

**Comment by quynhcvn** [comment]
Hi,

This bug happened when I Added a new Task:

  1.  In [Occurrence], I selected "Daily - Triggers actions daily at the specified time." ⇒ No issue
  2.  Then selected Time and Days ⇒ No issue
  3.  On "Select Action", I selected "Run PHP script" ⇒ No issue
  4.  Select PHP Script Path, then Error message happened.

Here is some capture for your reference:
[cid:794eaf47-a5b0-4b70-97a5-2c0e5e66073a]
[cid:eea31ff4-54f2-4be6-96cb-be7fb5c745f7]

WordPress version: 5.9.1
PHP version: 8.0.9

Thanks,
Frank.

________________________________

**Comment by quynhcvn** [comment]
Hi,

I tried with your suggestion, and it works:

$_iLastRunTime = round( ( integer ) $nLastRunTime );

Thanks.
Frank.

________________________________

**Comment by michaeluno** [comment]
I could confirm this. Thank you for the report.
