### ISSUE TITLE
Custom Tasks time out

### ISSUE THREAD

**Issue by fastmover** [michaeluno/Task-Scheduler#2]
Trying to develop a custom task, and the page just sits there and loads until it times out.

**Comment by michaeluno** [comment]
Hello,

Sorry,  I do not understand your problem.

>  and the page just sits there 

Which page are you specifically referring to?

**Comment by fastmover** [comment]
Nevermind, I can't get it to work.  I wrote a custom plugin for this to call a function in my plugin, and it doesn't seem to get to the DoWork method in the Thread class.
