### ISSUE TITLE
Deleting posts by tags

### ISSUE THREAD

**Issue by onlinemitch1** [michaeluno/Task-Scheduler#3]
Deleting posts using the "tags" taxonomy does not work. I select the tag for the posts I want to delete then click "create" and it appears to refresh the page and deselect the tags. The same thing happens when clicking the "back" button.

When I choose "all posts" or "categories" for the taxonomy and create the task everything appears to work fine. I have even tried creating a task to delete by category then editing it to delete by tags but the same issue occurs with the "back" and "update" buttons.

**Comment by onlinemitch1** [comment]
Ok, so I went back through and deleted all my tags that didn't have any posts (a couple hundred) and retried creating a task to delete by tags and it worked. I'm not sure why or how this affected it but it did.

**Comment by michaeluno** [comment]
Hi,

Sounds like an issue of `max_input_vars`. Once I had a user who could not save settings. His site had lots of taxonomy terms and a low value of `max_input_vars`. After increasing it, the form started to save the options. 

So you may try increasing the value of `max_input_vars` set in `php.ini`.

**Comment by onlinemitch1** [comment]
Thank you, I will do that if the problem arises again.
