### ISSUE TITLE
Delete Tasks Running Longer Than Specified Time?

### ISSUE THREAD

**Issue by Mwesome** [michaeluno/Task-Scheduler#4]
Would it be possible for you to add the functionality to delete a task which has been running logner than a time we specify?

Sometimes the scripts i run end with a fatal error or run out memory but the task routine is not deleted thus i have to go in and delete the task.

Thank  you for this awesome plugin!

P.S 
If you could tell me where to look i might be able to do it myself.
The code look very complicated to me.
Still a beginner!

**Comment by michaeluno** [comment]
Hi,

I've uploaded a development branch which includes an option to run a hung routine handler. 

Download: https://github.com/michaeluno/Task-Scheduler/archive/1.1.0b.zip

To enable it, create a task normally. In the task listing table, click on the Edit action link. Find the option named, `Handling Hung Routines` and choose the option.

Let me know if it works for you.

**Comment by michaeluno** [comment]
v1.1.0 has been released.
