### ISSUE TITLE
Error on Task List page

### ISSUE THREAD

**Issue by mynamavi** [michaeluno/Task-Scheduler#8]
Hi
I activated the plugin and gone to task list page so this error  is coming:
Fatal error: Call to a member function render_screen_reader_content() on null in /public_html/wp-admin/includes/class-wp-list-table.php on line 405

All the other pages are working fine. 

http://awesomescreenshot.com/06461edf3f

**Comment by michaeluno** [comment]
Hi,

I suspect you have a plugin/theme that interferes with the WordPress built-in screen object. What I can suggest you is to run the Task Scheduler plugin on a clean installed test site without any plugins and with the default theme only. Then see if you get the same error. If not, install and activate the theme you use on the site having a problem. If you don't get the error, install and activate plugins you use on the problematic site one by one and keep continuing until you get the error.

At some point, you'll see the error and tell me which one causes it.

**Comment by michaeluno** [comment]
Closing the topic due to inactivity.
